version: "3"
services:
  api:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 256M
      restart_policy:
        condition: on-failure
  proxy:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 128M
      restart_policy:
        condition: on-failure
  visualizer:
    deploy:
      placement:
        constraints: [node.role == manager]