version: "3"
services:
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8084:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - network1
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - manifold_data:/manifold_data/postgresql/data
    networks:
      - network1
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.7
    ports:
      - "9200:9200"
    networks:
      - network1
  redis: 
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - manifold_data:/manifold_data/redis
    networks:
      - network1
  api:
    image: manifoldscholar/manifold_api:${MANIFOLD_TAG}
    volumes:
      - manifold_data:/manifold_data
      - manifold_sockets:/manifold_sockets
    environment:
      - DOMAIN=localhost
      - RAILS_DB_NAME=postgres
      - RAILS_DB_USER=postgres
      - RAILS_DB_HOST=postgres
      - BOXEN_POSTGRESQL_PORT=5432
      - RAILS_REDIS_URL=redis://redis:6379
      - RACK_ENV=development
      - RAILS_ENV=development
      - RAILS_SECRET_KEY=f673814a9129dd345a9d3b0b34847eac04d25dc1127f21292c7d4bada6c3bdc2d83709f0ba8ec510efc9ee22b5993f1429259934aa71c5db8f64a4325af107a9
    command: bin/manifold start api
    networks:
      - network1
  proxy:
      image: manifoldscholar/manifold_proxy:${MANIFOLD_TAG}
      volumes:
        - manifold_data:/manifold_data
        - manifold_sockets:/manifold_sockets
      ports:
        - "4000:80"
      networks:
        - network1

volumes:
  manifold_data:
  manifold_sockets:

networks:
  network1:
